language: java
jdk:
- openjdk8

addons:
   sonarcloud:
      organization: juliandavis7-github
      token: travis encrypt 0ed64a6725da7bcbac78155c9dbab637fb9acb32

script:
- ant build
- sonar-scanner
